im:
  gate:
    port: 8090
  auth:
    port: 8081
    ip: localhost

spring:
    redis:
        database: 0      # Redis数据库索引（默认为0）
        host: localhost  # Redis服务器地址
        port: 6379       # Redis服务器连接端口
        password:        # Redis服务器连接密码（默认为空）
        timeout: 3000       # 连接超时时间（毫秒）
        pool:
          max-active: 100  # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 20    # 连接池中的最大空闲连接
          max-wait: 6000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 10    # 连接池中的最小空闲连接
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://39.106.133.40/ims?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root

server:
  context-path: /ims/