package com.xylink.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPrivateChatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CPrivateChat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userId = 1;</code>
     */
    String getUserId();
    /**
     * <code>string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string destId = 2;</code>
     */
    String getDestId();
    /**
     * <code>string destId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <code>bytes content = 3;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>.CPrivateChat.ChatType chatType = 4;</code>
     */
    int getChatTypeValue();
    /**
     * <code>.CPrivateChat.ChatType chatType = 4;</code>
     */
    CPrivateChat.ChatType getChatType();

    /**
     * <code>.CPrivateChat.DataType dataType = 5;</code>
     */
    int getDataTypeValue();
    /**
     * <code>.CPrivateChat.DataType dataType = 5;</code>
     */
    CPrivateChat.DataType getDataType();

    /**
     * <code>int32 seqNum = 6;</code>
     */
    int getSeqNum();

    /**
     * <code>int64 ts = 7;</code>
     */
    long getTs();
  }
  /**
   * Protobuf type {@code CPrivateChat}
   */
  public  static final class CPrivateChat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CPrivateChat)
      CPrivateChatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CPrivateChat.newBuilder() to construct.
    private CPrivateChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CPrivateChat() {
      userId_ = "";
      destId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      chatType_ = 0;
      dataType_ = 0;
      seqNum_ = 0;
      ts_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CPrivateChat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              destId_ = s;
              break;
            }
            case 26: {

              content_ = input.readBytes();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              chatType_ = rawValue;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 48: {

              seqNum_ = input.readInt32();
              break;
            }
            case 56: {

              ts_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_CPrivateChat_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_CPrivateChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CPrivateChat.class, Builder.class);
    }

    /**
     * Protobuf enum {@code CPrivateChat.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TXT = 0;</code>
       */
      TXT(0),
      /**
       * <code>VOICE = 1;</code>
       */
      VOICE(1),
      /**
       * <code>VIDEO = 2;</code>
       */
      VIDEO(2),
      /**
       * <code>IMG = 3;</code>
       */
      IMG(3),
      /**
       * <code>HYBRID = 4;</code>
       */
      HYBRID(4),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TXT = 0;</code>
       */
      public static final int TXT_VALUE = 0;
      /**
       * <code>VOICE = 1;</code>
       */
      public static final int VOICE_VALUE = 1;
      /**
       * <code>VIDEO = 2;</code>
       */
      public static final int VIDEO_VALUE = 2;
      /**
       * <code>IMG = 3;</code>
       */
      public static final int IMG_VALUE = 3;
      /**
       * <code>HYBRID = 4;</code>
       */
      public static final int HYBRID_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return TXT;
          case 1: return VOICE;
          case 2: return VIDEO;
          case 3: return IMG;
          case 4: return HYBRID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CPrivateChat.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CPrivateChat.DataType)
    }

    /**
     * Protobuf enum {@code CPrivateChat.ChatType}
     */
    public enum ChatType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ONE2ONE = 0;</code>
       */
      ONE2ONE(0),
      /**
       * <code>ONE2MANY = 1;</code>
       */
      ONE2MANY(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ONE2ONE = 0;</code>
       */
      public static final int ONE2ONE_VALUE = 0;
      /**
       * <code>ONE2MANY = 1;</code>
       */
      public static final int ONE2MANY_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ChatType valueOf(int value) {
        return forNumber(value);
      }

      public static ChatType forNumber(int value) {
        switch (value) {
          case 0: return ONE2ONE;
          case 1: return ONE2MANY;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ChatType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ChatType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ChatType>() {
              public ChatType findValueByNumber(int number) {
                return ChatType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return CPrivateChat.getDescriptor().getEnumTypes().get(1);
      }

      private static final ChatType[] VALUES = values();

      public static ChatType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ChatType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CPrivateChat.ChatType)
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile Object userId_;
    /**
     * <code>string userId = 1;</code>
     */
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 2;
    private volatile Object destId_;
    /**
     * <code>string destId = 2;</code>
     */
    public String getDestId() {
      Object ref = destId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      }
    }
    /**
     * <code>string destId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      Object ref = destId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 3;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int CHATTYPE_FIELD_NUMBER = 4;
    private int chatType_;
    /**
     * <code>.CPrivateChat.ChatType chatType = 4;</code>
     */
    public int getChatTypeValue() {
      return chatType_;
    }
    /**
     * <code>.CPrivateChat.ChatType chatType = 4;</code>
     */
    public ChatType getChatType() {
      ChatType result = ChatType.valueOf(chatType_);
      return result == null ? ChatType.UNRECOGNIZED : result;
    }

    public static final int DATATYPE_FIELD_NUMBER = 5;
    private int dataType_;
    /**
     * <code>.CPrivateChat.DataType dataType = 5;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.CPrivateChat.DataType dataType = 5;</code>
     */
    public DataType getDataType() {
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int SEQNUM_FIELD_NUMBER = 6;
    private int seqNum_;
    /**
     * <code>int32 seqNum = 6;</code>
     */
    public int getSeqNum() {
      return seqNum_;
    }

    public static final int TS_FIELD_NUMBER = 7;
    private long ts_;
    /**
     * <code>int64 ts = 7;</code>
     */
    public long getTs() {
      return ts_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
      }
      if (!getDestIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destId_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(3, content_);
      }
      if (chatType_ != ChatType.ONE2ONE.getNumber()) {
        output.writeEnum(4, chatType_);
      }
      if (dataType_ != DataType.TXT.getNumber()) {
        output.writeEnum(5, dataType_);
      }
      if (seqNum_ != 0) {
        output.writeInt32(6, seqNum_);
      }
      if (ts_ != 0L) {
        output.writeInt64(7, ts_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
      }
      if (!getDestIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destId_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (chatType_ != ChatType.ONE2ONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, chatType_);
      }
      if (dataType_ != DataType.TXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, dataType_);
      }
      if (seqNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, seqNum_);
      }
      if (ts_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, ts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CPrivateChat)) {
        return super.equals(obj);
      }
      CPrivateChat other = (CPrivateChat) obj;

      boolean result = true;
      result = result && getUserId()
          .equals(other.getUserId());
      result = result && getDestId()
          .equals(other.getDestId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && chatType_ == other.chatType_;
      result = result && dataType_ == other.dataType_;
      result = result && (getSeqNum()
          == other.getSeqNum());
      result = result && (getTs()
          == other.getTs());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CHATTYPE_FIELD_NUMBER;
      hash = (53 * hash) + chatType_;
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      hash = (37 * hash) + SEQNUM_FIELD_NUMBER;
      hash = (53 * hash) + getSeqNum();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CPrivateChat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPrivateChat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPrivateChat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPrivateChat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPrivateChat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CPrivateChat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CPrivateChat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPrivateChat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPrivateChat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CPrivateChat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CPrivateChat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CPrivateChat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CPrivateChat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CPrivateChat)
        CPrivateChatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Chat.internal_static_CPrivateChat_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Chat.internal_static_CPrivateChat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CPrivateChat.class, Builder.class);
      }

      // Construct using Chat.CPrivateChat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        destId_ = "";

        content_ = com.google.protobuf.ByteString.EMPTY;

        chatType_ = 0;

        dataType_ = 0;

        seqNum_ = 0;

        ts_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Chat.internal_static_CPrivateChat_descriptor;
      }

      public CPrivateChat getDefaultInstanceForType() {
        return CPrivateChat.getDefaultInstance();
      }

      public CPrivateChat build() {
        CPrivateChat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CPrivateChat buildPartial() {
        CPrivateChat result = new CPrivateChat(this);
        result.userId_ = userId_;
        result.destId_ = destId_;
        result.content_ = content_;
        result.chatType_ = chatType_;
        result.dataType_ = dataType_;
        result.seqNum_ = seqNum_;
        result.ts_ = ts_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CPrivateChat) {
          return mergeFrom((CPrivateChat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CPrivateChat other) {
        if (other == CPrivateChat.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getDestId().isEmpty()) {
          destId_ = other.destId_;
          onChanged();
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.chatType_ != 0) {
          setChatTypeValue(other.getChatTypeValue());
        }
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        if (other.getSeqNum() != 0) {
          setSeqNum(other.getSeqNum());
        }
        if (other.getTs() != 0L) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CPrivateChat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CPrivateChat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>string userId = 1;</code>
       */
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object destId_ = "";
      /**
       * <code>string destId = 2;</code>
       */
      public String getDestId() {
        Object ref = destId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string destId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destId = 2;</code>
       */
      public Builder setDestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destId = 2;</code>
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <code>string destId = 2;</code>
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 3;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 3;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private int chatType_ = 0;
      /**
       * <code>.CPrivateChat.ChatType chatType = 4;</code>
       */
      public int getChatTypeValue() {
        return chatType_;
      }
      /**
       * <code>.CPrivateChat.ChatType chatType = 4;</code>
       */
      public Builder setChatTypeValue(int value) {
        chatType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CPrivateChat.ChatType chatType = 4;</code>
       */
      public ChatType getChatType() {
        ChatType result = ChatType.valueOf(chatType_);
        return result == null ? ChatType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CPrivateChat.ChatType chatType = 4;</code>
       */
      public Builder setChatType(ChatType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        chatType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CPrivateChat.ChatType chatType = 4;</code>
       */
      public Builder clearChatType() {
        
        chatType_ = 0;
        onChanged();
        return this;
      }

      private int dataType_ = 0;
      /**
       * <code>.CPrivateChat.DataType dataType = 5;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.CPrivateChat.DataType dataType = 5;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.CPrivateChat.DataType dataType = 5;</code>
       */
      public DataType getDataType() {
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.CPrivateChat.DataType dataType = 5;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.CPrivateChat.DataType dataType = 5;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private int seqNum_ ;
      /**
       * <code>int32 seqNum = 6;</code>
       */
      public int getSeqNum() {
        return seqNum_;
      }
      /**
       * <code>int32 seqNum = 6;</code>
       */
      public Builder setSeqNum(int value) {
        
        seqNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seqNum = 6;</code>
       */
      public Builder clearSeqNum() {
        
        seqNum_ = 0;
        onChanged();
        return this;
      }

      private long ts_ ;
      /**
       * <code>int64 ts = 7;</code>
       */
      public long getTs() {
        return ts_;
      }
      /**
       * <code>int64 ts = 7;</code>
       */
      public Builder setTs(long value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ts = 7;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CPrivateChat)
    }

    // @@protoc_insertion_point(class_scope:CPrivateChat)
    private static final CPrivateChat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CPrivateChat();
    }

    public static CPrivateChat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPrivateChat>
        PARSER = new com.google.protobuf.AbstractParser<CPrivateChat>() {
      public CPrivateChat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPrivateChat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CPrivateChat> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CPrivateChat> getParserForType() {
      return PARSER;
    }

    public CPrivateChat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CPrivateChat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CPrivateChat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\nchat.proto\"\226\002\n\014CPrivateChat\022\016\n\006userId\030" +
      "\001 \001(\t\022\016\n\006destId\030\002 \001(\t\022\017\n\007content\030\003 \001(\014\022(" +
      "\n\010chatType\030\004 \001(\0162\026.CPrivateChat.ChatType" +
      "\022(\n\010dataType\030\005 \001(\0162\026.CPrivateChat.DataTy" +
      "pe\022\016\n\006seqNum\030\006 \001(\005\022\n\n\002ts\030\007 \001(\003\">\n\010DataTy" +
      "pe\022\007\n\003TXT\020\000\022\t\n\005VOICE\020\001\022\t\n\005VIDEO\020\002\022\007\n\003IMG" +
      "\020\003\022\n\n\006HYBRID\020\004\"%\n\010ChatType\022\013\n\007ONE2ONE\020\000\022" +
      "\014\n\010ONE2MANY\020\001B\006B\004Chatb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CPrivateChat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CPrivateChat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CPrivateChat_descriptor,
        new String[] { "UserId", "DestId", "Content", "ChatType", "DataType", "SeqNum", "Ts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
